// Code Generated by Sidekick is for learning and experimentation purposes only.

// Sample data structure - replace with API calls
const sampleArticles = [
    {
        id: 1,
        headline: "Egypt Mediates Ceasefire Negotiations in Gaza Strip",
        summary: "Egyptian officials have intensified diplomatic efforts to broker a humanitarian ceasefire between conflicting parties. Cairo has hosted multiple rounds of talks with regional stakeholders.",
        source: "Al-Ahram",
        sourceType: "egyptian",
        url: "https://example.com/article1",
        publishedAt: "2 hours ago"
    },
    {
        id: 2,
        headline: "Rafah Crossing Remains Critical Humanitarian Corridor",
        summary: "Egypt continues to manage the flow of humanitarian aid through the Rafah border crossing. Officials report increased coordination with international relief organizations.",
        source: "Egypt Independent",
        sourceType: "egyptian",
        url: "https://example.com/article2",
        publishedAt: "4 hours ago"
    },
    {
        id: 3,
        headline: "Regional Summit Discusses Humanitarian Crisis Response",
        summary: "Egypt hosted Arab League representatives to coordinate regional response efforts. The meeting focused on delivering essential supplies and medical assistance to affected populations.",
        source: "Al-Jazeera",
        sourceType: "regional",
        url: "https://example.com/article3",
        publishedAt: "6 hours ago"
    },
    {
        id: 4,
        headline: "Egyptian Foreign Minister Meets With UN Envoy",
        summary: "High-level discussions took place in Cairo regarding peacekeeping efforts and civilian protection measures. Both parties emphasized the need for immediate de-escalation.",
        source: "Middle East Eye",
        sourceType: "regional",
        url: "https://example.com/article4",
        publishedAt: "8 hours ago"
    },
    {
        id: 5,
        headline: "Humanitarian Aid Convoys Coordinated Through Egyptian Territory",
        summary: "Egypt has facilitated the passage of multiple international aid convoys destined for Gaza. The Egyptian Red Crescent is working alongside international partners to expedite delivery.",
        source: "Mada Masr",
        sourceType: "egyptian",
        url: "https://example.com/article5",
        publishedAt: "10 hours ago"
    },
    {
        id: 6,
        headline: "Cairo Peace Initiative Gains Regional Support",
        summary: "Egypt's proposed framework for sustainable peace has received backing from several Arab nations. The initiative emphasizes humanitarian concerns and long-term stability.",
        source: "The National",
        sourceType: "regional",
        url: "https://example.com/article6",
        publishedAt: "12 hours ago"
    },
    {
        id: 7,
        headline: "Egyptian Military Reinforces Sinai Border Security",
        summary: "Additional security measures have been implemented along the Sinai Peninsula border areas. Officials cite the need for enhanced monitoring during the regional crisis.",
        source: "Al-Masry Al-Youm",
        sourceType: "egyptian",
        url: "https://example.com/article7",
        publishedAt: "14 hours ago"
    },
    {
        id: 8,
        headline: "International Community Acknowledges Egypt's Mediation Role",
        summary: "Multiple nations have recognized Egypt's crucial position as a mediator and facilitator of humanitarian assistance. Diplomatic sources praise Cairo's balanced approach.",
        source: "Arab News",
        sourceType: "regional",
        url: "https://example.com/article8",
        publishedAt: "16 hours ago"
    },
    {
        id: 9,
        headline: "Medical Supplies Transit Egyptian Ports for Gaza",
        summary: "Shipments of essential medical equipment and pharmaceuticals have arrived at Egyptian ports for immediate transfer. The Ministry of Health is coordinating distribution efforts.",
        source: "Daily News Egypt",
        sourceType: "egyptian",
        url: "https://example.com/article9",
        publishedAt: "18 hours ago"
    },
    {
        id: 10,
        headline: "Egypt Proposes Extended Humanitarian Pause Framework",
        summary: "A comprehensive proposal for extended ceasefire periods has been presented to all parties involved. The framework includes provisions for civilian safety and aid distribution.",
        source: "Al-Monitor",
        sourceType: "regional",
        url: "https://example.com/article10",
        publishedAt: "20 hours ago"
    },
    {
        id: 11,
        headline: "Egyptian Civil Society Organizations Mobilize Aid Efforts",
        summary: "Grassroots organizations across Egypt have launched fundraising campaigns and volunteer initiatives. Collection centers have been established in major cities.",
        source: "Cairo Scene",
        sourceType: "egyptian",
        url: "https://example.com/article11",
        publishedAt: "22 hours ago"
    },
    {
        id: 12,
        headline: "Regional Intelligence Cooperation Strengthens Under Egyptian Leadership",
        summary: "Egypt has coordinated intelligence-sharing agreements among regional partners to enhance security cooperation. The initiative aims to prevent conflict spillover.",
        source: "Gulf News",
        sourceType: "regional",
        url: "https://example.com/article12",
        publishedAt: "1 day ago"
    }
];

let currentFilter = 'all';
let displayedArticles = 12;

// Initialize page
document.addEventListener('DOMContentLoaded', function() {
    updateLastUpdated();
    renderArticles();
    setupFilters();
    setupLoadMore();
    
    // Update time every minute
    setInterval(updateLastUpdated, 60000);
});

function updateLastUpdated() {
    const now = new Date();
    const timeString = now.toLocaleString('en-US', { 
        month: 'short', 
        day: 'numeric', 
        hour: '2-digit', 
        minute: '2-digit' 
    });
    document.getElementById('updateTime').textContent = timeString;
}

function renderArticles() {
    const newsGrid = document.getElementById('newsGrid');
    let articlesToShow = sampleArticles;
    
    // Apply filter
    if (currentFilter !== 'all') {
        articlesToShow = sampleArticles.filter(article => {
            if (currentFilter === 'egypt') return article.sourceType === 'egyptian';
            if (currentFilter === 'regional') return article.sourceType === 'regional';
            if (currentFilter === 'international') return article.sourceType === 'international';
            return true;
        });
    }
    
    // Limit display
    articlesToShow = articlesToShow.slice(0, displayedArticles);
    
    if (articlesToShow.length === 0) {
        newsGrid.innerHTML = '<div class="loading">No articles found for this filter.</div>';
        return;
    }
    
    newsGrid.innerHTML = articlesToShow.map(article => `
        <div class="article-card" onclick="window.open('${article.url}', '_blank')">
            <span class="article-source ${article.sourceType}">${article.source}</span>
            <h2 class="article-headline">${article.headline}</h2>
            <p class="article-summary">${article.summary}</p>
            <div class="article-meta">
                <span class="article-time">${article.publishedAt}</span>
                <a href="${article.url}" class="article-link" target="_blank" onclick="event.stopPropagation()">Read More →</a>
            </div>
        </div>
    `).join('');
    
    // Show/hide load more button
    const loadMoreBtn = document.getElementById('loadMore');
    if (articlesToShow.length < sampleArticles.length) {
        loadMoreBtn.style.display = 'block';
    } else {
        loadMoreBtn.style.display = 'none';
    }
}

function setupFilters() {
    const filterButtons = document.querySelectorAll('.filter-btn');
    
    filterButtons.forEach(button => {
        button.addEventListener('click', function() {
            // Update active state
            filterButtons.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            // Update filter and re-render
            currentFilter = this.dataset.source;
            displayedArticles = 12;
            renderArticles();
        });
    });
}

function setupLoadMore() {
    document.getElementById('loadMore').addEventListener('click', function() {
        displayedArticles += 12;
        renderArticles();
    });
}

// ============================================
// API INTEGRATION SECTION
// ============================================


// To fetch real news, uncomment and modify this section:

async function fetchRealNews() {
    try {
        // Option 1: NewsAPI.org
        const apiKey = 'fb92ba752d2544879e51112bfb4b6576';
        const query = 'Egypt AND (Gaza OR "Middle East" OR conflict OR ceasefire)';
        const sources = 'al-jazeera-english'; // Add more sources separated by commas
        
        const response = await fetch(
            `https://newsapi.org/v2/everything?q=${encodeURIComponent(query)}&sources=${sources}&apiKey=${apiKey}&language=en&sortBy=publishedAt`
        );
        
        const data = await response.json();
        
        if (data.status === 'ok') {
            // Transform API data to match our format
            return data.articles.map(article => ({
                id: article.url,
                headline: article.title,
                summary: article.description || article.content?.substring(0, 200) + '...',
                source: article.source.name,
                sourceType: determineSourceType(article.source.name),
                url: article.url,
                publishedAt: formatTime(article.publishedAt)
            }));
        }
    } catch (error) {
        console.error('Error fetching news:', error);
        return sampleArticles; // Fallback to sample data
    }
}

function determineSourceType(sourceName) {
    const egyptianSources = ['Al-Ahram', 'Egypt Independent', 'Mada Masr', 'Al-Masry Al-Youm', 'Daily News Egypt'];
    const regionalSources = ['Al-Jazeera', 'Middle East Eye', 'Al-Monitor', 'Arab News', 'The National'];
    const internationalSources = ['BBC', 'CBS News', 'CNN', 'CNBC', 'NPR'];

    if (egyptianSources.some(s => sourceName.includes(s))) return 'egyptian';
    if (regionalSources.some(s => sourceName.includes(s))) return 'regional';
    return 'international';
}

function formatTime(dateString) {
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now - date;
    const diffHrs = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);
    
    if (diffHrs < 1) return 'Just now';
    if (diffHrs < 24) return `${diffHrs} hours ago`;
    if (diffDays === 1) return '1 day ago';
    return `${diffDays} days ago`;
}

// Replace sampleArticles with API call:
// fetchRealNews().then(articles => {
//     sampleArticles = articles;
//     renderArticles();
// });

