// Code Generated by Sidekick is for learning and experimentation purposes only.
async function fetchRealNews() {
    try {
        // Use GNews instead - it doesn't need CORS proxy
        const apiKey = '708a165d65a792abdc53a525adf84301'; // Get from https://gnews.io
        const query = 'Egypt Middle East conflict';
        
        const response = await fetch(
            `https://gnews.io/api/v4/search?q=${encodeURIComponent(query)}&lang=en&max=20&apikey=${apiKey}`
        );
        
        if (!response.ok) {
            throw new Error('API request failed');
        }
        
        const data = await response.json();
        
        if (data.articles && data.articles.length > 0) {
            const transformedArticles = data.articles.map(article => ({
                id: article.url,
                headline: article.title,
                summary: article.description || 'No summary available.',
                source: article.source.name,
                sourceType: determineSourceType(article.source.name),
                url: article.url,
                publishedAt: formatTime(article.publishedAt)
            }));
            
            return transformedArticles;
        }
        
        return sampleArticles; // Fallback to sample data
        
    } catch (error) {
        console.error('Error fetching news:', error);
        return sampleArticles;
    }
}

// Make sure this runs when page loads
document.addEventListener('DOMContentLoaded', function() {
    updateLastUpdated();
    setupFilters();
    setupLoadMore();
    
    // Fetch real news
    fetchRealNews().then(articles => {
        sampleArticles = articles;
        renderArticles();
    });
    
    setInterval(updateLastUpdated, 60000);
});

