// Code Generated by Sidekick is for learning and experimentation purposes only.

// Sample data structure - will be replaced by API data
let sampleArticles = [
    {
        id: 1,
        headline: "Egypt Mediates Ceasefire Negotiations in Gaza Strip",
        summary: "Egyptian officials have intensified diplomatic efforts to broker a humanitarian ceasefire between conflicting parties. Cairo has hosted multiple rounds of talks with regional stakeholders.",
        source: "Al-Ahram",
        sourceType: "egyptian",
        url: "https://example.com/article1",
        publishedAt: "2 hours ago"
    },
    {
        id: 2,
        headline: "Rafah Crossing Remains Critical Humanitarian Corridor",
        summary: "Egypt continues to manage the flow of humanitarian aid through the Rafah border crossing. Officials report increased coordination with international relief organizations.",
        source: "Egypt Independent",
        sourceType: "egyptian",
        url: "https://example.com/article2",
        publishedAt: "4 hours ago"
    },
    {
        id: 3,
        headline: "Regional Summit Discusses Humanitarian Crisis Response",
        summary: "Egypt hosted Arab League representatives to coordinate regional response efforts. The meeting focused on delivering essential supplies and medical assistance to affected populations.",
        source: "Al-Jazeera",
        sourceType: "regional",
        url: "https://example.com/article3",
        publishedAt: "6 hours ago"
    }
];

let currentFilter = 'all';
let displayedArticles = 12;

// ============================================
// HELPER FUNCTIONS (Defined First)
// ============================================

function updateLastUpdated() {
    const now = new Date();
    const timeString = now.toLocaleString('en-US', { 
        month: 'short', 
        day: 'numeric', 
        hour: '2-digit', 
        minute: '2-digit' 
    });
    const timeElement = document.getElementById('updateTime');
    if (timeElement) {
        timeElement.textContent = timeString;
    }
}

function determineSourceType(sourceName) {
    const egyptianSources = ['Al-Ahram', 'Egypt Independent', 'Mada Masr', 'Al-Masry Al-Youm', 'Daily News Egypt', 'Ahram'];
    const regionalSources = ['Al-Jazeera', 'Middle East Eye', 'Al-Monitor', 'Arab News', 'The National', 'Gulf News'];
    
    const lowerSource = sourceName.toLowerCase();
    
    if (egyptianSources.some(s => lowerSource.includes(s.toLowerCase()))) return 'egyptian';
    if (regionalSources.some(s => lowerSource.includes(s.toLowerCase()))) return 'regional';
    return 'international';
}

function formatTime(dateString) {
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now - date;
    const diffHrs = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);
    
    if (diffHrs < 1) return 'Just now';
    if (diffHrs < 24) return `${diffHrs} hours ago`;
    if (diffDays === 1) return '1 day ago';
    if (diffDays < 7) return `${diffDays} days ago`;
    return date.toLocaleDateString();
}

function renderArticles() {
    const newsGrid = document.getElementById('newsGrid');
    if (!newsGrid) return;
    
    let articlesToShow = sampleArticles;
    
    // Apply filter
    if (currentFilter !== 'all') {
        articlesToShow = sampleArticles.filter(article => {
            if (currentFilter === 'egypt') return article.sourceType === 'egyptian';
            if (currentFilter === 'regional') return article.sourceType === 'regional';
            if (currentFilter === 'international') return article.sourceType === 'international';
            return true;
        });
    }
    
    // Limit display
    articlesToShow = articlesToShow.slice(0, displayedArticles);
    
    if (articlesToShow.length === 0) {
        newsGrid.innerHTML = '<div class="loading">No articles found for this filter.</div>';
        return;
    }
    
    newsGrid.innerHTML = articlesToShow.map(article => `
        <div class="article-card" onclick="window.open('${article.url}', '_blank')">
            <span class="article-source ${article.sourceType}">${article.source}</span>
            <h2 class="article-headline">${article.headline}</h2>
            <p class="article-summary">${article.summary}</p>
            <div class="article-meta">
                <span class="article-time">${article.publishedAt}</span>
                <a href="${article.url}" class="article-link" target="_blank" onclick="event.stopPropagation()">Read More →</a>
            </div>
        </div>
    `).join('');
    
    // Show/hide load more button
    const loadMoreBtn = document.getElementById('loadMore');
    if (loadMoreBtn) {
        if (displayedArticles < sampleArticles.length) {
            loadMoreBtn.style.display = 'block';
        } else {
            loadMoreBtn.style.display = 'none';
        }
    }
}

function setupFilters() {
    const filterButtons = document.querySelectorAll('.filter-btn');
    
    filterButtons.forEach(button => {
        button.addEventListener('click', function() {
            // Update active state
            filterButtons.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            // Update filter and re-render
            currentFilter = this.dataset.source;
            displayedArticles = 12;
            renderArticles();
        });
    });
}

function setupLoadMore() {
    const loadMoreBtn = document.getElementById('loadMore');
    if (loadMoreBtn) {
        loadMoreBtn.addEventListener('click', function() {
            displayedArticles += 12;
            renderArticles();
        });
    }
}

// ============================================
// API INTEGRATION
// ============================================

async function fetchRealNews() {
    try {
        // OPTION 1: GNews API (Replace YOUR_API_KEY with your actual key)
        const apiKey = '708a165d65a792abdc53a525adf84301';
        const query = 'Egypt Middle East conflict Gaza';
        
        const response = await fetch(
            `https://gnews.io/api/v4/search?q=${encodeURIComponent(query)}&lang=en&max=20&apikey=${apiKey}`
        );
        
        if (!response.ok) {
            throw new Error(`API Error: ${response.status}`);
        }
        
        const data = await response.json();
        
        if (data.articles && data.articles.length > 0) {
            return data.articles.map(article => ({
                id: article.url,
                headline: article.title,
                summary: article.description || 'No summary available.',
                source: article.source.name,
                sourceType: determineSourceType(article.source.name),
                url: article.url,
                publishedAt: formatTime(article.publishedAt)
            }));
        }
        
        console.log('No articles found, using sample data');
        return sampleArticles;
        
    } catch (error) {
        console.error('Error fetching news:', error);
        console.log('Falling back to sample data');
        return sampleArticles;
    }
}

// ============================================
// INITIALIZATION
// ============================================

document.addEventListener('DOMContentLoaded', function() {
    console.log('Page loaded, initializing...');
    
    // Set up UI components
    updateLastUpdated();
    setupFilters();
    setupLoadMore();
    
    // Update time every minute
    setInterval(updateLastUpdated, 60000);
    
    // Fetch and display news
    
    fetchRealNews().then(articles => {
        console.log(`Loaded ${articles.length} articles`);
        sampleArticles = articles;
        renderArticles();
    }).catch(error => {
        console.error('Failed to load news:', error);
        renderArticles(); // Show sample data on error
    });
    
    
    // COMMENT OUT THIS LINE when you uncomment the API code above
    // renderArticles();
});
